import { forwardRef } from "react";

function SidebarIcon({ icon }) {
  if (icon === "inventory") {
    return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M4 7.5h16M4 12h16M4 16.5h10" strokeLinecap="round" /><path d="M17 15.5l1.8 1.8L21 14.6" strokeLinecap="round" strokeLinejoin="round" /></svg>;
  }
  if (icon === "treasury") {
    return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M4 8.5 12 4l8 4.5" strokeLinecap="round" strokeLinejoin="round" /><path d="M6 9.5v7.5M12 9.5v7.5M18 9.5v7.5M4 19.5h16" strokeLinecap="round" /></svg>;
  }
  return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M5 7h14v10H5z" rx="2" /><path d="M8 10.5h8M8 13.5h5" strokeLinecap="round" /></svg>;
}

export function Panel({ id, title, description, action, children }) { return <article id={id} className="panel-shell rounded-[30px] p-5 shadow-panel backdrop-blur"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="panel-title text-xl font-semibold">{title}</h2><p className="panel-description mt-1 text-sm">{description}</p></div>{action}</div>{children}</article>; }
export function ThemeToggle({ theme, themes, onChange, orientation = "horizontal", compact = false }) {
  const isVertical = orientation === "vertical";
  return (
    <div className={`theme-toggle ${isVertical ? "theme-toggle-vertical" : "theme-toggle-horizontal"} ${compact ? "theme-toggle-compact" : ""} inline-flex gap-2 rounded-[28px] px-2 py-2`}>
      {Object.entries(themes).map(([value, config]) => (
        <button key={value} type="button" onClick={(event) => onChange(value, event)} className={`theme-pill rounded-full px-3 py-2 text-xs font-semibold uppercase tracking-[0.18em] transition ${theme === value ? "theme-pill-active" : "theme-pill-idle"} ${isVertical ? "theme-pill-block w-full" : ""}`}>
          <span className="theme-pill-label">{config.label}</span>
        </button>
      ))}
    </div>
  );
}
export function LogoUploadField({ label, logoDataUrl, onSelect, onClear }) { return <div><span className="field-label mb-2 block text-sm font-medium">{label}</span><label className="field-input flex cursor-pointer items-center justify-center rounded-2xl border-dashed px-4 py-4 text-center text-sm"><input type="file" accept="image/*" className="hidden" onChange={onSelect} /><span>{logoDataUrl ? "Reemplazar logo" : "Seleccionar imagen"}</span></label>{logoDataUrl ? <div className="soft-card mt-3 flex items-center justify-between gap-4 rounded-2xl p-3"><img src={logoDataUrl} alt="Logo comercio" className="h-14 w-14 rounded-xl object-contain" /><button type="button" onClick={onClear} className="section-button section-button-idle rounded-full px-3 py-2 text-xs font-semibold transition">Quitar logo</button></div> : <div className="panel-description mt-2 text-xs">Opcional. Se guarda localmente y se usa en el ticket.</div>}</div>; }
export function SidebarLink({ item, active, collapsed = false, onClick, elementId }) { return <button id={elementId} type="button" onClick={onClick} className={`sidebar-link flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm font-semibold transition ${active ? "sidebar-link-active" : "sidebar-link-idle"} ${collapsed ? "sidebar-link-collapsed justify-center px-2" : ""}`} aria-label={item.label} title={item.label}><span className="sidebar-badge flex h-10 w-10 items-center justify-center rounded-xl text-[11px] font-bold uppercase tracking-[0.18em]"><SidebarIcon icon={item.icon} /></span><span className={collapsed ? "sr-only" : ""}>{item.label}</span></button>; }
export function MetricCard({ label, value, emphasis = false }) { return <div className="metric-card rounded-2xl px-4 py-4"><div className="metric-label text-xs uppercase tracking-[0.22em]">{label}</div><div className={`mt-2 text-2xl font-semibold ${emphasis ? "metric-value-emphasis" : "metric-value"}`}>{value}</div></div>; }
export function StatusPanel({ message, error }) { if (!message && !error) return null; return <div className={`status-panel mt-4 rounded-2xl border px-4 py-3 text-sm ${error ? "status-panel-error" : "status-panel-success"}`}>{error || message}</div>; }
export function ScannerStatus({ state }) { const states = { ready: { label: "Lector listo", className: "success-soft text-emerald-100" }, processing: { label: "Procesando lectura", className: "info-box text-sky-100" }, success: { label: "Lectura confirmada", className: "success-soft text-emerald-100" }, warning: { label: "Código nuevo", className: "warning-box text-amber-100" }, error: { label: "Revisar lectura", className: "danger-box text-rose-100" }, blocked: { label: "Doble lectura bloqueada", className: "warning-box text-orange-100" } }; const current = states[state] ?? states.ready; return <div className={`rounded-2xl px-4 py-2 text-xs font-semibold uppercase tracking-[0.18em] ${current.className}`}>{current.label}</div>; }
export function EmptyState({ children }) { return <div className="empty-state rounded-2xl border border-dashed px-4 py-10 text-center text-sm">{children}</div>; }
export function CategorySelect({ label, value, categories, onChange }) { return <label className="block"><span className="field-label mb-2 block text-sm font-medium">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="field-input w-full rounded-2xl px-4 py-3 text-sm outline-none transition">{categories.length === 0 ? <option value="General">General</option> : categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select></label>; }
export const InputField = forwardRef(function InputField({ label, ...props }, ref) { return <label className="block"><span className="field-label mb-2 block text-sm font-medium">{label}</span><input ref={ref} {...props} className="field-input w-full rounded-2xl px-4 py-3 text-sm outline-none transition" /></label>; });
export function SelectField({ label, options, ...props }) { return <label className="block"><span className="field-label mb-2 block text-sm font-medium">{label}</span><select {...props} className="field-input w-full rounded-2xl px-4 py-3 text-sm outline-none transition">{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; }
export function InventoryTable({ items, onEdit, onDelete, formatMoney, selectedIds = [], onToggleSelect, onToggleSelectAll }) { return <div className="overflow-x-auto"><table className="inventory-table min-w-full border-separate border-spacing-y-2 text-left text-sm"><thead className="content-muted text-xs uppercase tracking-[0.2em]"><tr><th className="px-3 py-2"><input type="checkbox" checked={items.length > 0 && items.every((item) => selectedIds.includes(item.id))} onChange={(event) => onToggleSelectAll?.(event.target.checked)} aria-label="Seleccionar todos los productos visibles" /></th><th className="px-3 py-2">Producto</th><th className="px-3 py-2">Código</th><th className="px-3 py-2">Categoría</th><th className="px-3 py-2">Proveedor</th><th className="px-3 py-2">Stock</th><th className="px-3 py-2">Costo</th><th className="px-3 py-2">Venta</th><th className="px-3 py-2">Acciones</th></tr></thead><tbody>{items.map((item) => { const isLow = item.quantity <= item.min_quantity; return <tr key={item.id} className="inventory-row"><td className="rounded-l-2xl px-3 py-3"><input type="checkbox" checked={selectedIds.includes(item.id)} onChange={() => onToggleSelect?.(item.id)} aria-label={`Seleccionar ${item.name}`} /></td><td className="px-3 py-3"><div className="content-strong font-medium">{item.name}</div><div className="content-muted text-xs">{item.category}</div></td><td className="inventory-code px-3 py-3 font-mono text-xs">{item.code}</td><td className="content-default px-3 py-3">{item.category}</td><td className="content-default px-3 py-3">{item.provider || "Sin proveedor"}</td><td className="px-3 py-3"><span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${isLow ? "danger-box text-rose-100" : "success-soft text-emerald-100"}`}>{item.quantity} / mínimo {item.min_quantity}</span></td><td className="content-default px-3 py-3">{formatMoney(item.cost_price)}</td><td className="content-default px-3 py-3">{formatMoney(item.sale_price)}</td><td className="rounded-r-2xl px-3 py-3"><div className="flex flex-wrap gap-2"><button type="button" onClick={() => onEdit(item)} className="section-button section-button-idle rounded-full px-3 py-1 text-xs font-medium transition">Editar</button><button type="button" onClick={() => onDelete(item)} className="danger-button rounded-full px-3 py-1 text-xs font-medium transition">Eliminar</button></div></td></tr>; })}</tbody></table></div>; }
export function MovementCard({ movement }) { const isOut = movement.quantity_delta < 0; return <div className="card-surface rounded-2xl p-4"><div className="flex items-center justify-between gap-3"><div><div className="content-strong font-medium">{movement.item_name}</div><div className="content-muted text-xs uppercase tracking-[0.18em]">{movement.movement_type} · {movement.reference}</div></div><div className={`rounded-full px-3 py-1 text-xs font-semibold ${isOut ? "danger-box text-rose-100" : "success-soft text-emerald-100"}`}>{isOut ? movement.quantity_delta : `+${movement.quantity_delta}`}</div></div></div>; }
export function CashSessionCard({ session, formatMoney, formatDateTime }) { const diff = Number(session.difference_amount || 0); const closed = session.closed_at ? formatDateTime(session.closed_at) : "Turno en curso"; return <div className="card-surface rounded-2xl p-4"><div className="flex items-center justify-between gap-3"><div><div className="content-strong font-medium">{session.status === "OPEN" ? "Caja abierta" : "Caja cerrada"}</div><div className="content-muted text-xs uppercase tracking-[0.18em]">Apertura: {formatDateTime(session.opened_at)}</div></div><div className={`rounded-full px-3 py-1 text-xs font-semibold ${diff < 0 ? "danger-box text-rose-100" : "success-soft text-emerald-100"}`}>{session.status === "OPEN" ? formatMoney(session.expected_cash_amount) : `${diff >= 0 ? "+" : ""}${formatMoney(diff)}`}</div></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div className="soft-card rounded-2xl px-4 py-3"><span className="content-faint block text-xs uppercase tracking-[0.18em]">Esperado</span><span className="content-strong mt-1 block font-medium">{formatMoney(session.expected_cash_amount)}</span></div><div className="soft-card rounded-2xl px-4 py-3"><span className="content-faint block text-xs uppercase tracking-[0.18em]">Real / cierre</span><span className="content-strong mt-1 block font-medium">{session.actual_cash_amount == null ? closed : formatMoney(session.actual_cash_amount)}</span></div></div>{session.notes ? <div className="soft-card content-default mt-4 rounded-2xl px-4 py-3 text-sm">{session.notes}</div> : null}</div>; }
export function ReportList({ title, rows, renderLabel, renderMeta }) { return <div className="soft-card rounded-2xl p-4"><h3 className="panel-description text-sm font-semibold uppercase tracking-[0.2em]">{title}</h3><div className="mt-3 space-y-3">{rows.length === 0 ? <EmptyState>Sin datos suficientes.</EmptyState> : rows.map((row) => <div key={renderLabel(row)} className="card-surface rounded-2xl px-4 py-3"><div className="content-strong font-medium">{renderLabel(row)}</div><div className="content-muted text-sm">{renderMeta(row)}</div></div>)}</div></div>; }
export function RecentSaleCard({ sale, formatMoney, formatDateTime }) { return <div className="card-surface rounded-2xl px-4 py-3"><div className="flex items-center justify-between gap-3"><div><div className="content-strong font-medium">{sale.item_name}</div><div className="content-muted text-xs uppercase tracking-[0.18em]">{sale.code} · {sale.category}</div></div><div className="text-right"><div className="content-strong font-medium">{formatMoney(sale.revenue)}</div><div className="content-muted text-xs">{sale.quantity} unidades</div></div></div><div className="mt-3 flex items-center justify-between gap-3"><div className="content-faint text-xs uppercase tracking-[0.18em]">{formatDateTime(sale.created_at)}</div><div className="section-button section-button-idle rounded-full px-3 py-1 text-[11px] font-semibold">{sale.payment_method}</div></div></div>; }
export function FeatureCard({ title, description }) { return <div className="feature-card rounded-2xl p-5"><div className="content-strong text-lg font-semibold">{title}</div><div className="auth-text mt-2 text-sm">{description}</div></div>; }
export function MiniStat({ label, value }) { return <div className="feature-card rounded-2xl p-5"><div className="panel-description text-xs uppercase tracking-[0.24em]">{label}</div><div className="content-strong mt-3 text-2xl font-semibold">{value}</div></div>; }
export function QuickAction({ title, description, onClick, emphasis = false }) { return <button type="button" onClick={onClick} className={`quick-action rounded-2xl p-5 text-left transition ${emphasis ? "quick-action-emphasis" : "quick-action-default"}`}><div className="content-strong text-lg font-semibold">{title}</div><div className="panel-description mt-2 text-sm">{description}</div></button>; }
export function StatusRow({ label, value, strong = false }) { return <div className="soft-card flex items-center justify-between rounded-2xl px-4 py-3"><span className="panel-description text-sm">{label}</span><span className={`text-sm font-semibold ${strong ? "content-strong" : "content-default"}`}>{value}</span></div>; }
export function ShortcutHint({ children }) { return <div className="shortcut-hint rounded-2xl px-4 py-3 text-sm">{children}</div>; }
export function InsightCard({ title, value, helper }) { return <div className="soft-card rounded-2xl p-4"><div className="panel-description text-xs uppercase tracking-[0.2em]">{title}</div><div className="content-strong mt-2 text-xl font-semibold">{value}</div><div className="content-muted mt-2 text-sm">{helper}</div></div>; }
export function SummaryBadge({ label, value }) { return <div className="soft-card rounded-2xl px-4 py-3 text-right"><div className="panel-description text-[11px] uppercase tracking-[0.22em]">{label}</div><div className="content-strong mt-1 text-sm font-semibold">{value}</div></div>; }
export function MiniLine({ label, value }) { return <div className="flex items-center justify-between gap-3"><span className="panel-description text-sm">{label}</span><span className="content-strong text-sm font-semibold">{value}</span></div>; }
export function ActionCard({ title, description, subtle = false, children }) { return <div className={`action-card rounded-[28px] p-5 ${subtle ? "action-card-light" : "action-card-strong"}`}><div className="content-strong text-3xl font-semibold">{title}</div><div className="panel-description mt-2 text-sm">{description}</div><div className="mt-5">{children}</div></div>; }

function getDailySalesMetricConfig(metric) {
  if (metric === "profit") return { key: "profit", label: "Ganancia", format: (value, helpers) => helpers.formatMoney(value) };
  if (metric === "units_sold") return { key: "units_sold", label: "Unidades vendidas", format: (value, helpers) => helpers.formatInteger(value) };
  return { key: "revenue", label: "Recaudación", format: (value, helpers) => helpers.formatMoney(value) };
}

export function DailySalesChart({ rows, metric = "revenue", formatMoney, formatInteger }) {
  const helpers = { formatMoney, formatInteger };
  const config = getDailySalesMetricConfig(metric);
  const values = rows.map((row) => Number(row[config.key] || 0));
  const maxValue = Math.max(...values, 1);
  return <div className="daily-sales-chart"><div className="chart-grid">{rows.map((row) => { const currentValue = Number(row[config.key] || 0); return <div key={row.label} className="chart-column"><div className="chart-meta text-xs">{config.format(currentValue, helpers)}</div><div className="chart-bar-wrap"><div className="chart-bar" style={{ height: `${Math.max((currentValue / maxValue) * 100, 8)}%` }} title={`${config.label}: ${config.format(currentValue, helpers)}`} /></div><div className="chart-label text-xs">{row.label}</div><div className="chart-foot text-[11px]">{row.sales_count} ventas</div></div>; })}</div></div>;
}

