import { ActionCard, CashSessionCard, DailySalesChart, EmptyState, InsightCard, InputField, Panel, RecentSaleCard, ReportList, MetricCard, SelectField } from "../components/AppUI";

export default function TreasurySection(props) {
  const { cashSummary, submitCashClose, cashCloseForm, setCashCloseForm, submitCashOpen, cashOpenForm, setCashOpenForm, saleForm, setSaleForm, submitSale, treasuryFilter, setTreasuryFilter, treasuryPreset, treasuryMetric, setTreasuryMetric, applyTreasuryPreset, applyTreasuryFilter, clearTreasuryFilter, exportTreasuryCsv, printTreasurySummary, saving, treasuryFilterActive, reports, dailySales, handleText, formatMoney, formatInteger, formatDate, formatDateTime, paymentMethodOptions } = props;
  return (
    <div className="space-y-6">
      <section className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]">
        <Panel title="Control de caja" description="Abrí o cerrá el turno, registrá ventas y seguí el balance del día en tiempo real.">
          <div className="grid gap-4 lg:grid-cols-2">
            <ActionCard title="Abrir caja" description="Iniciá el turno con el saldo base verificado."><form className="space-y-3" onSubmit={submitCashOpen}><InputField label="Monto inicial" name="opening_amount" type="number" min="0" step="0.01" value={cashOpenForm.opening_amount} onChange={handleText(setCashOpenForm)} /><InputField label="Observaciones de apertura" name="notes" value={cashOpenForm.notes} onChange={handleText(setCashOpenForm)} /><button type="submit" disabled={saving || Boolean(cashSummary.current_session)} className="primary-button w-full rounded-2xl px-4 py-3 text-sm font-semibold">Abrir caja</button></form></ActionCard>
            <ActionCard title="Cerrar caja" description="Finalizá el turno y registrá el monto real del cierre." subtle><form className="space-y-3" onSubmit={submitCashClose}><InputField label="Monto real al cierre" name="actual_cash_amount" type="number" min="0" step="0.01" value={cashCloseForm.actual_cash_amount} onChange={handleText(setCashCloseForm)} /><InputField label="Observaciones de cierre" name="notes" value={cashCloseForm.notes} onChange={handleText(setCashCloseForm)} /><button type="submit" disabled={saving || !cashSummary.current_session} className="secondary-button w-full rounded-2xl px-4 py-3 text-sm font-semibold">Cerrar caja</button></form></ActionCard>
          </div>
          <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Caja física esperada" value={formatMoney(cashSummary.expected_cash_now)} /><MetricCard label="Ventas en efectivo" value={formatMoney(cashSummary.cash_revenue)} /><MetricCard label="Ventas virtuales" value={formatMoney(cashSummary.non_cash_revenue)} /><MetricCard label="Recaudación total" value={formatMoney(cashSummary.today_revenue)} /></div>
        </Panel>
        <Panel title="Registrar venta" description="Impacta stock, recaudación y margen estimado automáticamente.">{!cashSummary.current_session ? <div className="info-box mb-4 rounded-2xl px-4 py-3 text-sm">Antes de vender, abrí la caja del día para que la operación quede auditada en tesorería.</div> : null}<form className="space-y-4" onSubmit={submitSale}><InputField label="Código de barras" name="code" value={saleForm.code} onChange={handleText(setSaleForm)} /><InputField label="Cantidad" name="amount" type="number" min="1" value={saleForm.amount} onChange={handleText(setSaleForm)} /><InputField label="Precio unitario opcional" name="unit_price" type="number" min="0" step="0.01" value={saleForm.unit_price} onChange={handleText(setSaleForm)} /><SelectField label="Medio de pago" name="payment_method" value={saleForm.payment_method} onChange={handleText(setSaleForm)} options={paymentMethodOptions} /><button type="submit" disabled={saving || !cashSummary.current_session} className="primary-button w-full rounded-2xl px-4 py-3 text-sm font-semibold">Registrar venta</button></form></Panel>
      </section>
      <section className="grid gap-6 xl:grid-cols-[1.08fr_0.92fr]">
        <Panel title="Pulso diario de ventas" description="Compará la evolución diaria de la métrica clave dentro del período actual." action={<div className="flex flex-col gap-3"><div className="range-chip-group flex flex-wrap gap-2">{[{ id: "7d", label: "7 días" }, { id: "30d", label: "30 días" }, { id: "month", label: "Mes actual" }, { id: "all", label: "Todo" }].map((preset) => <button key={preset.id} type="button" onClick={() => applyTreasuryPreset(preset.id)} className={`rounded-full px-4 py-2 text-xs font-semibold transition ${treasuryPreset === preset.id ? "section-button section-button-active" : "section-button section-button-idle"}`}>{preset.label}</button>)}</div><div className="metric-chip-group flex flex-wrap gap-2">{[{ id: "revenue", label: "Recaudación" }, { id: "profit", label: "Ganancia" }, { id: "units_sold", label: "Unidades" }].map((metric) => <button key={metric.id} type="button" onClick={() => setTreasuryMetric(metric.id)} className={`rounded-full px-4 py-2 text-xs font-semibold transition ${treasuryMetric === metric.id ? "section-button section-button-active" : "section-button section-button-idle"}`}>{metric.label}</button>)}</div></div>}>
          {dailySales.length === 0 ? <EmptyState>Todavía no hay suficientes ventas para dibujar el gráfico diario.</EmptyState> : <DailySalesChart rows={dailySales} metric={treasuryMetric} formatMoney={formatMoney} formatInteger={formatInteger} />}
        </Panel>
        <Panel title="Resumen ejecutivo" description="Indicadores rápidos para tomar decisiones sin salir de tesorería."><div className="treasury-summary-grid grid gap-4 sm:grid-cols-2"><InsightCard title="Ticket promedio" value={cashSummary.today_sales_count > 0 ? formatMoney(cashSummary.today_revenue / cashSummary.today_sales_count) : formatMoney(0)} helper="Promedio de venta registrado en el período visible." /><InsightCard title="Margen estimado" value={cashSummary.today_revenue > 0 ? `${Math.round((cashSummary.today_profit / cashSummary.today_revenue) * 100)}%` : "0%"} helper="Basado en recaudación y costo declarado." /><InsightCard title="Caja actual" value={cashSummary.current_session ? "Abierta" : "Cerrada"} helper={cashSummary.current_session ? "Hay un turno operativo en curso." : "No hay turno activo en este momento."} /><InsightCard title="Ventas virtuales" value={formatMoney(cashSummary.non_cash_revenue)} helper={`${cashSummary.today_units_sold} unidades vendidas en el período.`} /></div></Panel>
      </section>
      <section className="grid gap-6 xl:grid-cols-[0.95fr_1.05fr]">
        <div className="space-y-6">
          <Panel title="Período de análisis" description="Filtrá tesorería por rango de fechas para revisar cierres y ventas." action={<div className="flex flex-wrap gap-2"><button type="button" onClick={exportTreasuryCsv} disabled={saving} className="section-button section-button-active rounded-full px-4 py-2 text-sm font-semibold transition">Descargar CSV</button><button type="button" onClick={printTreasurySummary} className="section-button section-button-idle rounded-full px-4 py-2 text-sm font-semibold transition">Imprimir resumen</button></div>}><form className="grid gap-4 md:grid-cols-2" onSubmit={applyTreasuryFilter}><InputField label="Desde" name="startDate" type="date" value={treasuryFilter.startDate} onChange={handleText(setTreasuryFilter)} /><InputField label="Hasta" name="endDate" type="date" value={treasuryFilter.endDate} onChange={handleText(setTreasuryFilter)} /><button type="submit" disabled={saving} className="primary-button rounded-2xl px-4 py-3 text-sm font-semibold">Aplicar filtro</button><button type="button" onClick={clearTreasuryFilter} className="section-button section-button-idle rounded-2xl px-4 py-3 text-sm font-semibold transition">Ver todo</button></form>{treasuryFilterActive ? <div className="info-box mt-4 rounded-2xl px-4 py-3 text-sm">Mostrando tesorería desde {treasuryFilter.startDate ? formatDate(treasuryFilter.startDate) : "el inicio"} hasta {treasuryFilter.endDate ? formatDate(treasuryFilter.endDate) : "hoy"}.</div> : null}</Panel>
          <Panel title="Jornadas registradas" description={treasuryFilterActive ? "Cierres y aperturas del período filtrado." : "Últimos cierres y turnos de caja registrados."}>{cashSummary.recent_sessions.length === 0 ? <EmptyState>No hay jornadas en ese período.</EmptyState> : <div className="space-y-3">{cashSummary.recent_sessions.map((session) => <CashSessionCard key={session.id} session={session} formatMoney={formatMoney} formatDateTime={formatDateTime} />)}</div>}</Panel>
        </div>
        <div className="space-y-6">
          <Panel title="Reportes inteligentes" description="Lectura rápida de recaudación, ganancia y comportamiento de ventas.">
            <div className="grid gap-4 lg:grid-cols-2"><ReportList title="Productos más vendidos" rows={reports.top_products} renderLabel={(row) => row.name} renderMeta={(row) => `${row.quantity} unidades · ${formatMoney(row.revenue)}`} /><ReportList title="Categorías más vendidas" rows={reports.top_categories} renderLabel={(row) => row.category} renderMeta={(row) => `${row.quantity} unidades · ${formatMoney(row.revenue)}`} /></div>
            <div className="soft-card mt-5 rounded-2xl p-4"><h3 className="panel-description text-sm font-semibold uppercase tracking-[0.2em]">Insights</h3><div className="mt-3 space-y-2">{reports.insights.length === 0 ? <EmptyState>Sin insights todavía.</EmptyState> : reports.insights.map((insight) => <div key={insight} className="success-soft rounded-2xl px-4 py-3 text-sm">{insight}</div>)}</div></div>
            <div className="mt-5"><h3 className="panel-description text-sm font-semibold uppercase tracking-[0.2em]">Últimas ventas del período</h3><div className="mt-3 space-y-3">{reports.recent_sales.length === 0 ? <EmptyState>No hay ventas en ese período.</EmptyState> : reports.recent_sales.map((sale) => <RecentSaleCard key={sale.id} sale={sale} formatMoney={formatMoney} formatDateTime={formatDateTime} />)}</div></div>
          </Panel>
        </div>
      </section>
    </div>
  );
}



